### PR TITLE
Travis: remove unsupported Ubuntu 16.10, fix CentOS 7 build

### LINKED ISSUE #103: configure script fails to find xenlight on CentOS
configure returned:
```
$ ./configure  --verbose
In file included from /usr/include/libxl.h:426:0,
                 from /tmp/configure48e13a.c:2:
/usr/include/libxl_uuid.h:27:23: fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>
                       ^
compilation terminated.
/tmp/configuredc2c2f.c: In function 'main':
/tmp/configuredc2c2f.c:5:3: error: too many arguments to function 'xc_domain_create'
   int r = xc_domain_create(0, 0, 0, 0, 0, 0);
   ^
In file included from /tmp/configuredc2c2f.c:2:0:
/usr/include/xenctrl.h:511:5: note: declared here
 int xc_domain_create(xc_interface *xch,
     ^
running: uname -m
Looking for xenctrl.h: ok
Looking for libxl_physinfo.outstanding_pages: missing
Looking for xen-4.5: ok
Looking for xen-4.6: ok
Looking for config parameter on xc_domain_create: missing
Looking for xc_domain_set_cores_per_socket: ok
Looking for xc_domain_save generation_id: missing
Looking for HVM_PARAM_VIRIDIAN: ok
Failure: we can't build anything without libxl from Xen 4.4 or greater
```
However, the library seems to be installed:
```
/usr/lib64/libxenlight.so.4.6.0
/usr/lib64/ocaml/stublibs/dllxenlight_stubs.so
/usr/lib64/ocaml/stublibs/dllxenlight_stubs.so.owner
/usr/lib64/ocaml/xenlight
/usr/lib64/ocaml/xenlight/xenlight.cmi
/usr/lib64/ocaml/xenlight/xenlight.cmx
/usr/lib64/ocaml/xenlight/libxenlight_stubs.a
/usr/lib64/ocaml/xenlight/xenlight.a
/usr/lib64/ocaml/xenlight/xenlight.cmxa
/usr/lib64/ocaml/xenlight/xenlight.cma
/usr/lib64/libxenlight.so
/usr/lib64/libxenlight.so.4.6
```

### PR DESCRIPTION
**Pull request by gaborigloi**
Fixes #103

### CODE REVIEW

**Comment by mseri** [comment]
Can you make a PR to update the opam file in xs-opam please?

**Comment by gaborigloi** [comment]
@mseri Shall I release it as 0.10.0? For some reason we kept incrementing the bugfix version number, but [semver says](http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase) we should increment the minor.

**Comment by gaborigloi** [comment]
@mseri oh sorry, my bad, it's pinned to master in xs-opam. But I think we should still make a new release at one point.

**Comment by gaborigloi** [comment]
@mseri raised https://github.com/xapi-project/xs-opam/pull/114

**Comment by mseri** [comment]
I think a new release should be `0.10.0` because we removed `cpuid_check`

**Comment by gaborigloi** [comment]
Raised https://github.com/xapi-project/ocaml-xen-lowlevel-libs/pull/105 to release `0.10.0`.

**Pull request merged**
