### PR TITLE
Prepare to release v0.9.32

### PR DESCRIPTION
**Pull request by djs55**
* fixes for compiling on XenServer
* fix META and static linking
* add travis CI support for multiple distros
* fix compilation on musl-based systems like alpine
* add depexts for fedora, rhel and oraclelinux

### CODE REVIEW

**Comment by djs55** [comment]
On `debian-testing`:
```
### stdout ###
# /usr/include/xenctrl.h:491:5: note: declared here
# [...]
# lib/xenctrl_stubs.c: In function 'stub_map_foreign_range':
# lib/xenctrl_stubs.c:975:15: warning: implicit declaration of function 'xc_map_foreign_range' [-Wimplicit-function-declaration]
#   intf->addr = xc_map_foreign_range(_H(xch), c_dom,
#                ^~~~~~~~~~~~~~~~~~~~
# lib/xenctrl_stubs.c:975:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
#   intf->addr = xc_map_foreign_range(_H(xch), c_dom,
#              ^
# Command exited with code 2.
# Makefile:27: recipe for target 'build' failed
### stderr ###
```

**Comment by mseri** [comment]
I think we need to add also xenlight and xentoollog for xen-4.7 and xen-4.8 to fix the compilation

**Comment by jonludlam** [comment]
Thanks @djs55 - hopefully I've fixed the xen-4.7 issue, so I've submitted PR#95 with these changes rebased on top of that.

**Pull request closed without merging**
