### PR TITLE
Fix META and statically linking with ld

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by sevenEng** [comment]
came across this problem when trying to adapting jitsu to work against xen backend, the generated Makefile by `mirage configure -t xen` failed to include linkage of the c stubs for these libs

**Comment by lindig** [comment]
Could you in your commit message or here describe the crucial part? The commit includes many updates from auto-generates files. I assume it is adding

    XMETAExtraLines:    xen_linkopts = "-lxenctrl_stubs"

to META.

**Comment by dinosaure** [comment]
Yes, about the dirty change, firstly you use `oasis` in static mode, a part of this dirty commit is generated by `oasis setup` (maybe a good improvement is to move to the dynamic mode or use another distribution system). The white-space change is generated by `xenlight-4.4/prepare` (called by `configure.ml` needed by `oasis setup`) - and, in your repository you are both `xenlight_stubs.c` and `xenlight_stubs.c.in`.

I don't know the best way to clean this PR. I follow only the process of distribution.

But the goal of this PR is just to add automatically (by `oasis`) the line:
```
XMETAExtraLines:    xen_linkopts = "-lxenctrl_stubs"
```
in a META file, yes - to link statically the C stubs (automatically for sure).

**Comment by euanh** [comment]
We are in the process of removing oasis autogenerated files from our packages and instead depending on oasis and using it to generate them in the setup phase.   We have not done that for this package yet.

Please split your commit into two parts:
 1. The change to the _oasis file
 2. The changes in autogenerated files caused by running oasis setup

**Comment by euanh** [comment]
@lindig I've seen whitespace changes happen when using a slightly different version of oasis to regenerate the autogenerated files.

**Comment by dinosaure** [comment]
Done :+1:

**Comment by euanh** [comment]
Thanks @dinosaure

**Pull request merged**
