### PR TITLE
Support xen-4.9 (as found in ubuntu 17.10)

### LINKED ISSUE #106: This does not work with recent xen
Installing it on a ubuntu 17.10 fails with multiple gcc warning/errors

### PR DESCRIPTION
**Pull request by jonludlam**
Fixes #106 

Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

### CODE REVIEW

**Comment by edwintorok** [comment]
Nice, I'll finally be able to install xen-api-client at home :)
Any idea why Travis is not happy though? `xenlight/caml_types.h:258:23: error: 'LIBXL_DISK_FORMAT_QED' undeclared `

**Comment by jonludlam** [comment]
yeah, that's probably a real issue, I need to fix this PR.

**Comment by mseri** [comment]
Should we add travis tests with a recent fedora/ubuntu?

**Comment by jonludlam** [comment]
Yes, I think the more distros the better. Not for this PR though :-)

**Pull request merged**
